package app.umbra.ui.model;

/** User-facing error categories. Technical detail is kept separate and only shown on request. */
public enum ErrorKind {
    NO_CONNECTION, RELAY_UNAVAILABLE, TURN_UNAVAILABLE, CONTACT_UNVERIFIED, IDENTITY_CHANGED, CONTACT_BLOCKED,
    DEVICE_REVOKED, CAMERA_DENIED, MICROPHONE_DENIED, LOCATION_DENIED, BLUETOOTH_DENIED, VAULT_LOCKED,
    STORAGE_FAILED, CALL_ENDED, BLUETOOTH_UNAVAILABLE, FEATURE_PENDING, OFFLINE_EDITION, GENERIC
}
