"""Coordination regression: a peer's success must not close the other peer's receipt pump."""
import sys
from pathlib import Path
import unittest
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from run_bluetooth_emulation import both_drained, both_quiescent, finish_drained_peers


class BluetoothDrainTests(unittest.TestCase):
    def test_requires_two_live_drained_peers(self):
        done="nearbyStage=verified\nnearbyStage=drained\n"
        self.assertTrue(both_drained([done,done]))
        for reports in ([],[done],[done,"nearbyStage=verified"],[done,done+"nearbyResult=FAIL: receipt missing"],
                        ["nearbyResult=PASS: old premature success",done]):
            self.assertFalse(both_drained(reports))

    def test_no_peer_closes_while_other_has_late_duplicate_receipt_write(self):
        # Reproduce the host ordering from34e0374: both reported drained, but
        # the second endpoint is still pumping an ACK regenerated by a duplicate.
        peers = ('listener', 'dialer')
        reports = {peer: 'nearbyStage=drained\n' for peer in peers}
        pending = {'listener': False, 'dialer': True}
        commands = []
        def send(peer, command):
            if command == 'finish':
                self.assertFalse(any(pending.values()), 'peer closed before late receipt retired')
                self.assertTrue(all('nearbyStage=quiescent' in x for x in reports.values()))
            elif command == 'quiesce':
                pending[peer] = False
                reports[peer] += 'nearbyStage=quiescent\n'
            else:
                self.fail('Unexpected command')
            commands.append((peer, command))
        def wait(predicate, seconds, reason):
            self.assertGreater(seconds, 0)
            self.assertLessEqual(seconds, 60)
            self.assertTrue(predicate(list(reports.values())), reason)
        finish_drained_peers(peers, send, wait)
        self.assertEqual(commands, [('listener','quiesce'),('dialer','quiesce'),
                                    ('listener','finish'),('dialer','finish')])

    def test_quiescence_requires_both_confirmations_and_no_failure(self):
        drained = 'nearbyStage=drained\n'
        quiet = drained + 'nearbyStage=quiescent\n'
        self.assertFalse(both_quiescent([drained, quiet]))
        self.assertFalse(both_quiescent([quiet, quiet + 'nearbyResult=FAIL: closed']))
        self.assertTrue(both_quiescent([quiet, quiet]))

    def test_quiescence_failure_never_releases_either_peer(self):
        commands = []
        def wait(predicate, seconds, reason):
            if predicate is both_quiescent:
                raise TimeoutError('writer did not quiesce')
        with self.assertRaisesRegex(TimeoutError, 'did not quiesce'):
            finish_drained_peers(('a','b'), lambda peer, cmd: commands.append((peer,cmd)), wait)
        self.assertEqual(commands,[('a','quiesce'),('b','quiesce')])
