# AndroidJUnitRunner's FileTestStorage uses this Kotlin base class. The test APK
# treats Kotlin supplied by libsignal in the target as a library; shrinking it
# away causes NoClassDefFoundError before any test executes. This rule is only
# for mediaLab, not production release; UMBRA classes remain optimizable/renamable.
-keep,allowoptimization class kotlin.jvm.internal.Lambda { *; }
# TestDirCalculator initializes a Kotlin lazy value through the facade. Keep
# these three standard-library entry points, including inherited facade methods.
-keep,allowoptimization class kotlin.LazyKt { *; }
-keep,allowoptimization class kotlin.LazyKt__LazyJVMKt { *; }
-keep,allowoptimization class kotlin.LazyKt__LazyKt { *; }
-keep,allowoptimization interface kotlin.Lazy { *; }
# UMBRA API roots are generated by TraceReferences from only the media fixture.
